Repository KrzysiekK93/currency-exchange, pull requests merged in 2020-04, with the labels that each got.

#6 (feat): historical quotations
  package-lock.json
  package.json
  src/App.vue
  src/components/HistoricalQuotations.vue
  src/components/LastQuotations.vue
  src/components/LastQuotationsTable.vue
  src/store/index.js
  src/views/Home.vue
Labels: enhancement

#11 Feature/push currency rates to store
  src/components/quotations/last/LastQuotations.vue
  src/store/index.js
  src/views/Dashboard.vue
Labels: enhancement

#27 initial calculator
  src/components/Calculator.vue
  src/store/index.js
  src/views/Dashboard.vue
Labels: enhancement

#31 final calculator
  src/components/Calculator.vue
  src/store/index.js
Labels: enhancement

#39 data call is in main.js
  src/components/Calculator.vue
  src/components/quotations/last/LastQuotations.vue
  src/components/quotations/last/LastQuotationsTable.vue
  src/main.js
Labels: enhancement

#47 (feat)List all currency
  src/components/Calculator.vue
  src/views/Dashboard.vue
Labels: enhancement

#48 (feat): connect calculator to database
  src/components/AccountOperation.vue
  src/components/Calculator.vue
Labels: enhancement

#49 calc enhancement
  src/components/Calculator.vue
  src/views/Dashboard.vue
Labels: bug

#50 (fix):Deploy fix
  src/components/quotations/historical/HistoricalQuotations.vue
Labels: bug

#51 userinfo is displayed
  src/components/authentication/Register.vue
Labels: bug

#52 (fix): Remove unused code
  src/components/quotations/historical/HistoricalQuotations.vue
Labels: bug

#54 init documentation
  src/components/documentation/Goals.vue
  src/components/documentation/Pictures.vue
  src/components/documentation/Topic.vue
  src/components/shared/Header.vue
  src/router/index.js
  src/views/Dashboard.vue
  src/views/Documentation.vue
Labels: documentation

#55 (fix):css-issue
  src/components/Calculator.vue
  src/components/UserInfo.vue
  src/components/documentation/Goals.vue
  src/components/documentation/Pictures.vue
  src/components/documentation/Topic.vue
  src/components/quotations/last/LastQuotationsTable.vue
  src/components/shared/Header.vue
  src/views/Dashboard.vue
Labels: bug

#59 (fix):hamburger-fix
  src/components/shared/Header.vue
Labels: bug

#61 add links
  src/components/documentation/Goals.vue
  src/components/documentation/Links.vue
  src/components/documentation/Pictures.vue
  src/views/Documentation.vue
Labels: documentation
